# All-in-one image: Next.js web + Express API + the two Python microservices in a
# SINGLE container. The web is the only public process (listens on Railway's
# $PORT); the API and Python services run on fixed localhost ports inside the
# container. PostgreSQL is Railway's managed database (DATABASE_URL).
#
# Build context is the REPO ROOT (this Dockerfile lives there). Railway needs no
# root directory or custom Dockerfile path — it auto-detects /Dockerfile.
FROM node:22-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-venv openssl ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN corepack enable
WORKDIR /app

# The FullStackHub monorepo (Node web/api/shared + the Python services).
COPY FullStackHub/ ./

# Node deps (Prisma client is generated by the api postinstall) + the web build.
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @shipping-hub/web build

# Python deps for the two stateless services, in one shared virtualenv.
RUN python3 -m venv /opt/venv \
    && /opt/venv/bin/pip install --no-cache-dir \
       -r services/pricing/requirements.txt \
       -r services/labels/requirements.txt

# Internal wiring: every process shares the container's network over localhost,
# so these never need to be set in Railway.
ENV NODE_ENV=production \
    PORT=8080 \
    API_PORT=4000 \
    API_INTERNAL_URL=http://127.0.0.1:4000 \
    PRICING_SERVICE_URL=http://127.0.0.1:8001 \
    LABELS_SERVICE_URL=http://127.0.0.1:8002

COPY start.sh ./start.sh
EXPOSE 8080
CMD ["bash", "start.sh"]
